# travis-ci.org and coveralls definition for pyFileSec tests
language: python
python:
  - "2.7"
  - "2.6"
virtualenv:
  system_site_packages: true
before_install:
  - which openssl
  - /usr/bin/openssl version  # OpenSSL is pre-installed
  - py.test --version
  - sudo pwd > /home/travis/virtualenv/python2.7_with_system_site_packages/lib/python2.7/site-packages/pyfilesec.pth
  - sudo pwd > /home/travis/virtualenv/python2.6_with_system_site_packages/lib/python2.6/site-packages/pyfilesec.pth
install:
  - pip install -q coveralls --use-mirrors && export HAS_COVERALLS=1
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install -q argparse; fi
branches:
  only:
    - master
script: py.test -k-notravis --cov pyfilesec
after_success:
  - if [[ $HAS_COVERALLS ]]; then coveralls; fi
